[package]
name = "canvas-2d"
version = "0.1.0"
edition = "2021"

[features]
metal = ["skia-safe/metal"]
gl = ["skia-safe/gl"]
vulkan = ["skia-safe/vulkan"]

[dependencies]
canvas-core = { path = "../canvas-core", features = ["2d"] }
parking_lot = "0.12.3"
regex = "1.10.5"
base64 = "0.22.1"
encoding_rs = "0.8.34"
gl-bindings = { path = "../gl-bindings" }
csscolorparser = { git = "https://github.com/triniwiz/csscolorparser-rs.git", rev = "c8c7e86", features = ["named-colors"] }
log = "0.4.21"
skia-safe = { version = "0.75.0", features = ["gl", "textlayout"] }
bytes = "1.6.1"
env_logger = "0.11.2"
ash = { version = "0.38.0" }


[target.'cfg(target_os="ios")'.dependencies]
skia-safe = { version = "0.75.0", features = ["gl", "metal", "textlayout"] }


[target.'cfg(target_os="macos")'.dependencies]
skia-safe = { version = "0.75.0", features = ["gl", "metal", "textlayout"] }

[target.'cfg(target_os="android")'.dependencies]
skia-safe = { version = "0.75.0", features = ["gl", "vulkan", "textlayout"] }
ash = { version = "0.38.0" }