[package]
name = "canvas-2d"
version = "0.1.0"
edition = "2021"

[features]
metal = ["skia-safe/metal"]
gl = ["skia-safe/gl"]

[dependencies]
canvas-core = { path = "../canvas-core", features = ["2d"] }
parking_lot = "0.12.0"
regex = "1.10.3"
base64 = "0.22.0"
encoding_rs = "0.8.34"
gl-bindings = { path = "../gl-bindings" }
lazy_static = "1.4.0"
csscolorparser = { git = "https://github.com/triniwiz/csscolorparser-rs.git", rev = "c8c7e86", features = ["named-colors"] }
#rgb = { version = "0.8.37", features = ["argb"] }
log = "0.4.21"
once_cell = "1.8.0"
skia-safe = { version = "0.75.0", features = ["gl", "textlayout"] }
bytes = "1.5.0"
env_logger = "0.11.2"
