[workspace]
resolver = "2"

members = [
    "crates/gl-bindings",
    "crates/canvas-core",
    "crates/canvas-2d",
    "crates/canvas-webgl",
    "crates/canvas-android",
    "crates/canvas-ios",
    "crates/playground",
    "crates/canvas-c",
    "crates/canvas-svg"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
debug = false
incremental = false
strip = true


[workspace.dependencies.wgt]
package = "wgpu-types"
git = "https://github.com/gfx-rs/wgpu"
rev = "4f1a9b53deb053ca65f6a57e2e4c2b59e34ed1c2"

[workspace.dependencies]
env_logger = "0.11.5"
log = "0.4.22"
parking_lot = "0.12.3"
raw-window-handle = "0.6.2"
canvas-2d = { path = "./crates/canvas-2d" }
canvas-core = { path = "./crates/canvas-core" }
canvas-webgl = { path = "./crates/canvas-webgl" }
gl-bindings = { path = "./crates/gl-bindings" }
canvas-c = { path = "./crates/canvas-c" }
skia-safe = { version = "0.78.2", features = ["textlayout"] }
itertools = "0.13.0"
wgpu-core = { git = "https://github.com/gfx-rs/wgpu", rev = "4f1a9b53deb053ca65f6a57e2e4c2b59e34ed1c2", features = ["wgsl", "vulkan", "metal", "raw-window-handle"] }
wgpu-types = { git = "https://github.com/gfx-rs/wgpu", rev = "4f1a9b53deb053ca65f6a57e2e4c2b59e34ed1c2" }
ureq = "2.10.1"