[package]
name = "canvas-core"
version = "2.0.0"
authors = ["Osei Fortune <fortune.osei@yahoo.com>"]
edition = "2021"

[features]
2d = ["skia-safe", "skia-safe/gl"]

[dependencies]
gl-bindings = { path = "../gl-bindings" }
raw-window-handle = "0.5.2"
parking_lot = "0.12.0"
stb_image = { git = "https://github.com/triniwiz/rust-stb-image", rev = "869380b" }
skia-safe = { version = "0.72.0", features = ["gl", "textlayout"], optional = true }
once_cell = "1.19.0"
log = "0.4.21"

[target.'cfg(target_os = "ios")'.dependencies]
icrate = { version = "0.0.4", features = ["objc2", "Foundation", "Foundation_NSData"] }
core-foundation = "0.9.3"

[target.'cfg(target_os = "android")'.dependencies]
egl = "0.2.7"
glutin = "0.31.1"
android_log = "0.1.3"

[target.'cfg(target_os = "macos")'.dependencies]
winit = "0.29.4"
glutin-winit = "0.4.2"
glutin = "0.31.1"