[package]
name = "canvas-core"
version = "2.0.0"
authors = ["Osei Fortune <fortune.osei@yahoo.com>"]
edition = "2021"

[features]
2d = ["skia-safe", "skia-safe/gl"]

[dependencies]
gl-bindings = { path = "../gl-bindings" }
raw-window-handle = "0.5.0"
parking_lot = "0.12.0"
image = {version = "0.24.5", features = ["jpeg", "png", "gif", "rgb"]}
skia-safe = { version = "0.60.0", features = ["gl"], optional = true }
once_cell = "1.14.0"

#[target.'cfg(target_os = "ios")'.dependencies]
#icrate = "0.0.2"
#core-foundation = "0.9.3"

#[target.'cfg(target_os = "android")'.dependencies]
egl = "0.2.7"
glutin = "0.30.6"

#[target.'cfg(target_os = "macos")'.dependencies]
#winit = "0.28.1"
#glutin-winit = "0.3.0"
#glutin = { git = "https://github.com/triniwiz/glutin", rev = "b199cc2" }