[package]
name = "canvas-native"
version = "1.0.0"
authors = ["Osei Fortune <fortune.osei@yahoo.com>"]
edition = "2021"

[lib]
name = "canvasnative"
crate-type = ["cdylib", "staticlib"]

[build-dependencies]
bindgen = "0.61.0"
cmake = "0.1.44"
cc = "1.0.56"
regex = "1.5.6"

[dependencies]
regex = "1.5.6"
base64 = "0.13.0"
encoding_rs = "0.8.24"
gl-bindings = { version = "0.1.0", path = "../gl-bindings" }
lazy_static = "1.4.0"
css-color-parser = "0.1.2"
log = "0.4.8"
rand = "0.8.4"
skia-safe = { version = "0.56.1", features = ["gl", "svg"] }
stb = { git = "https://github.com/triniwiz/stb.git", rev = "3c7f87b", features = ["stb_image", "stb_image_write", "stb_image_resize"] }

parking_lot = "0.12.1"

[target.'cfg(target_os="android")'.dependencies]
#openssl = { version = "0.10.38", features = ["vendored"] }
android_logger = "0.11.1"
once_cell = "1.14.0"
libloading = "0.7"
ndk = {version = "0.7.0", features = ["bitmap"]}
jni = "0.20.0"



[target.'cfg(target_os="ios")'.dependencies]
cocoa = { version = "0.24.0" }
objc = { version = "0.2.4" }
block = "0.1.6"



