[package]
name = "canvas-core"
version = "2.0.0"
authors = ["Osei Fortune <fortune.osei@yahoo.com>"]
edition = "2021"

[features]
2d = ["skia-safe", "skia-safe/gl"]

[dependencies]
gl-bindings = { path = "../gl-bindings" }
glutin = { git = "https://github.com/triniwiz/glutin", rev = "b199cc2" }
raw-window-handle = "0.5.0"
parking_lot = "0.12.0"
image = "0.24.5"
skia-safe = { version = "0.58.0", features = ["gl"], optional = true }
once_cell = "1.14.0"

[target.'cfg(target_os="ios")'.dependencies]
cocoa = { version = "0.24.0" }
objc = { version = "0.2.4" }
objc-foundation = "0.1.1"
block = "0.1.6"
core-foundation = "0.9.3"
core-graphics-types = "0.1.1"


[target.'cfg(target_os="android")'.dependencies]
egl = "0.2.7"

[target.'cfg(target_os="mac")'.dependencies]
winit = "0.28.1"
glutin-winit = "0.3.0"