import { SVGElement } from './SVGElement';

const SVG_SPREADMETHOD_UNKNOWN = 0;
const SVG_SPREADMETHOD_PAD = 1;
const SVG_SPREADMETHOD_REFLECT = 2;
const SVG_SPREADMETHOD_REPEAT = 3;

export class SVGGradientElement extends SVGElement {
	static SVG_SPREADMETHOD_UNKNOWN = SVG_SPREADMETHOD_UNKNOWN;
	static SVG_SPREADMETHOD_PAD = SVG_SPREADMETHOD_PAD;
	static SVG_SPREADMETHOD_REFLECT = SVG_SPREADMETHOD_REFLECT;
	static SVG_SPREADMETHOD_REPEAT = SVG_SPREADMETHOD_REPEAT;
}
