package com.github.triniwiz.canvas.extensions;

import android.opengl.GLES30;


/**
 * Created by triniwiz on 5/1/20
 */
public class WEBGL_compressed_texture_etc {

    public int COMPRESSED_R11_EAC = GLES30.GL_COMPRESSED_R11_EAC;

    public int COMPRESSED_SIGNED_R11_EAC = GLES30.GL_COMPRESSED_SIGNED_R11_EAC;

    public int COMPRESSED_RG11_EAC = GLES30.GL_COMPRESSED_RG11_EAC;

    public int COMPRESSED_SIGNED_RG11_EAC = GLES30.GL_COMPRESSED_SIGNED_RG11_EAC;

    public int COMPRESSED_RGB8_ETC2 = GLES30.GL_COMPRESSED_RGB8_ETC2;

    public int COMPRESSED_RGBA8_ETC2_EAC = GLES30.GL_COMPRESSED_RGBA8_ETC2_EAC;

    public int COMPRESSED_SRGB8_ETC2 = GLES30.GL_COMPRESSED_SRGB8_ETC2;

    public int COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = GLES30.GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC;

    public int COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = GLES30.GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2;

    public int COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = GLES30.GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2;
}
