<Project>
  <PropertyGroup>
    <AppDisplayName>NSCanvas</AppDisplayName>
    <AppDescription>NativeScript Canvas — built with NativeScript on Windows.</AppDescription>
    <ApplicationManifest Condition="'$(ApplicationManifest)' == '' and Exists('$(MSBuildThisFileDirectory)app.manifest')">$(MSBuildThisFileDirectory)app.manifest</ApplicationManifest>
  </PropertyGroup>
</Project>
