[package]
name = "canvas-android"
version = "0.1.0"
edition = "2021"


[lib]
name = "canvasandroid"
crate-type = ["cdylib"]

[build-dependencies]
cxx-build = "1.0.73"
bindgen = "0.59.2"

[dependencies]
canvas-core = { path = "../canvas-core" , features = ["gl"]}
gl-bindings = { path = "../gl-bindings" }
cxx = "1.0.73"
ureq = "2.5.0"
parking_lot = "0.12.0"
egl = "0.2.7"
jni = "0.19.0"
libc = "0.2.121"
once_cell = "1.10.0"
utf16string = "0.2.0"
ndk = {version = "0.7.0", features = ["bitmap"]}
openssl = {version = "0.10.38", features = ["vendored"]}
libloading = "0.7.3"
