platform :ios, '13.0'


nsc_is_visionos = "#{__dir__} #{Dir.pwd}".include?('visionos')
unless nsc_is_visionos
  pod 'GDPerformanceView', :git => 'https://github.com/triniwiz/GDPerformanceView.git', :commit => 'c72cb61c719377413a656526222c2ef83ae9c073'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
