platform :ios, '13.0'

pod 'GDPerformanceView', :git => 'https://github.com/triniwiz/GDPerformanceView.git', :commit => 'c72cb61c719377413a656526222c2ef83ae9c073'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
