#ifndef CANVAS_SVG_C_H
#define CANVAS_SVG_C_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct RenderThread RenderThread;

typedef struct SvgDocument SvgDocument;

/**
 * Keeps the window, backend and size so `render` can rebuild the context in place after a
 * driver reset or GPU reclaim, which can happen while the window is still valid.
 */
typedef struct SvgGpuSurface SvgGpuSurface;

typedef struct SvgNode SvgNode;

struct SvgDocument *canvas_native_svg_document_create(void);

struct SvgDocument *canvas_native_svg_document_create_with_string(const char *svg);

void canvas_native_svg_document_release(struct SvgDocument *doc);

/**
 * Promotes a node out of the static content; null clears. See `SvgDocument::set_layer`.
 */
void canvas_native_svg_document_set_layer(struct SvgDocument *doc, const char *id);

/**
 * Drops the cached static raster; call when anything outside the promoted node changes.
 */
void canvas_native_svg_document_invalidate_backdrop(struct SvgDocument *doc);

/**
 * Views share one recording per frame; direct node mutations then need `invalidate_frames`.
 */
void canvas_native_svg_document_set_frame_sharing(struct SvgDocument *doc, bool enabled);

/**
 * Drops the shared recordings after a mutation the document could not see.
 */
void canvas_native_svg_document_invalidate_frames(struct SvgDocument *doc);

/**
 * `width`/`height` are physical pixels; `scale` maps logical (`set_container_size`) units onto them.
 */
void canvas_native_svg_document_render_to_buffer(struct SvgDocument *doc,
                                                 uint8_t *pixels,
                                                 uintptr_t pixels_len,
                                                 int32_t width,
                                                 int32_t height,
                                                 float scale);

/**
 * As above, into caller-owned pixels (e.g. a locked Android `Bitmap`) that may be row-padded.
 */
void canvas_native_svg_document_render_to_pixels(struct SvgDocument *doc,
                                                 uint8_t *pixels,
                                                 uintptr_t pixels_len,
                                                 int32_t width,
                                                 int32_t height,
                                                 uintptr_t row_bytes,
                                                 float scale);

void canvas_native_svg_document_set_container_size(struct SvgDocument *doc,
                                                   float width,
                                                   float height);

/**
 * Wrapped fresh each call with an empty children mirror.
 */
struct SvgNode *canvas_native_svg_document_root(struct SvgDocument *doc);

void canvas_native_svg_document_register_id(struct SvgDocument *doc,
                                            const char *id,
                                            const struct SvgNode *node);

void canvas_native_svg_document_unregister_id(struct SvgDocument *doc, const char *id);

/**
 * Resolves an id registered either by us or by Skia's parser.
 */
struct SvgNode *canvas_native_svg_document_get_element_by_id(struct SvgDocument *doc,
                                                             const char *id);

bool canvas_native_svg_document_has_animations(const struct SvgDocument *doc);

uintptr_t canvas_native_svg_document_animation_count(const struct SvgDocument *doc);

/**
 * Seconds until every animation ends; negative if any repeats indefinitely.
 */
double canvas_native_svg_document_animation_duration(const struct SvgDocument *doc);

double canvas_native_svg_document_current_time(const struct SvgDocument *doc);

/**
 * Returns a bitmask: bit 0 while anything is still animating (keep scheduling frames),
 * bit 1 when a value changed this frame (redraw).
 */
int32_t canvas_native_svg_document_set_current_time(struct SvgDocument *doc, double seconds);

struct SvgNode *canvas_native_svg_node_create(const char *tag);

struct SvgNode *canvas_native_svg_node_create_text(const char *text);

void canvas_native_svg_node_release(struct SvgNode *node);

char *canvas_native_svg_node_tag_name(const struct SvgNode *node);

bool canvas_native_svg_node_set_attribute(struct SvgNode *node,
                                          const char *name,
                                          const char *value);

char *canvas_native_svg_node_get_attribute(const struct SvgNode *node, const char *name);

void canvas_native_string_destroy(char *value);

/**
 * Does not take ownership of `child`: only its node handle is cloned into `parent`,
 * and the caller still releases `child` itself.
 */
bool canvas_native_svg_node_append_child(struct SvgNode *parent, const struct SvgNode *child);

/**
 * A text node's text, or null for any other node. Free with `canvas_native_string_destroy`.
 */
char *canvas_native_svg_node_get_text(const struct SvgNode *node);

/**
 * False for any node that is not a text node.
 */
bool canvas_native_svg_node_set_text(struct SvgNode *node, const char *text);

/**
 * Returns a fresh `SvgNode` the caller owns, or null on an out-of-range index.
 */
struct SvgNode *canvas_native_svg_node_remove_child(struct SvgNode *parent, uintptr_t index);

/**
 * `backend` is a `Backend` discriminant; pass 0 (auto) unless the user forced one.
 */
struct SvgGpuSurface *canvas_native_svg_gpu_create(void *window,
                                                   int32_t width,
                                                   int32_t height,
                                                   int32_t backend);

/**
 * Returns the `Backend` discriminant actually in use, or 0 for a null surface.
 */
int32_t canvas_native_svg_gpu_backend(const struct SvgGpuSurface *gpu);

void canvas_native_svg_gpu_resize(struct SvgGpuSurface *gpu, int32_t width, int32_t height);

/**
 * Returns a `FrameStatus` discriminant; only 3 (lost) means the GPU path is unusable.
 */
int32_t canvas_native_svg_gpu_render(struct SvgGpuSurface *gpu,
                                     struct SvgDocument *doc,
                                     float scale);

/**
 * The caller still owns the reference it passed to `create` and must release it after `destroy`.
 */
void *canvas_native_svg_gpu_window(const struct SvgGpuSurface *gpu);

/**
 * Simulates a context loss to exercise the recovery path.
 */
void canvas_native_svg_gpu_debug_lose_context(struct SvgGpuSurface *gpu);

void canvas_native_svg_gpu_destroy(struct SvgGpuSurface *gpu);

/**
 * Starts a render thread that owns its own GPU surface for `window`. Null means use the bitmap.
 */
struct RenderThread *canvas_native_svg_render_thread_create(void *window,
                                                            int32_t width,
                                                            int32_t height,
                                                            int32_t backend);

/**
 * Records `doc` on the calling thread (which owns it); only the display list crosses to the
 * render thread. Returns false when there was nothing to record.
 */
bool canvas_native_svg_render_thread_commit(struct RenderThread *render,
                                            struct SvgDocument *doc,
                                            int32_t width,
                                            int32_t height,
                                            float scale);

void canvas_native_svg_render_thread_resize(struct RenderThread *render,
                                            int32_t width,
                                            int32_t height);

/**
 * The `FrameStatus` of the last present, or -1 if nothing has presented since the last call.
 */
int32_t canvas_native_svg_render_thread_status(struct RenderThread *render);

/**
 * Blocks until the thread has torn down its surface, since the caller releases the window next.
 */
void canvas_native_svg_render_thread_destroy(struct RenderThread *render);

#endif  /* CANVAS_SVG_C_H */
