#ifndef CANVAS_IOS_H
#define CANVAS_IOS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

long long canvas_native_ios_create_webgl_context(void *view,
                                                 bool alpha,
                                                 bool antialias,
                                                 bool depth,
                                                 bool fail_if_major_performance_caveat,
                                                 int32_t power_preference,
                                                 bool premultiplied_alpha,
                                                 bool preserve_drawing_buffer,
                                                 bool stencil,
                                                 bool desynchronized,
                                                 bool xr_compatible,
                                                 uint32_t version);

bool canvas_native_ios_flush_webgl(int64_t context);

void canvas_native_ios_flush_2d_context(int64_t context);

void canvas_native_ios_present_drawable(int64_t context);

void canvas_native_ios_flush_2d_context_and_sync_cpu(int64_t context);

void canvas_native_ios_resize_context_2d(int64_t context, float width, float height);

int64_t canvas_native_ios_create_2d_context(void *view,
                                            int32_t width,
                                            int32_t height,
                                            bool alpha,
                                            float density,
                                            int32_t font_color,
                                            float ppi,
                                            int32_t direction);

void canvas_native_ios_update_2d_webgpu_surface(int64_t view,
                                                float width,
                                                float height,
                                                int64_t context);

void canvas_native_ios_update_webgl_surface(int64_t view,
                                            int32_t _width,
                                            int32_t _height,
                                            int64_t context);

void canvas_native_ios_release_webgl(int64_t context);

void canvas_native_ios_gl_make_current(int64_t context);

bool canvas_native_ios_image_asset_load_from_bytes(int64_t asset, uint8_t *bytes, uintptr_t size);

int64_t canvas_native_ios_context_create_pattern_raw(int64_t context,
                                                     int32_t width,
                                                     int32_t height,
                                                     uint8_t *bytes,
                                                     uintptr_t size,
                                                     const char *repetition);

bool canvas_native_ios_context_draw_image_dx_dy_with_bytes(int64_t context,
                                                           uint8_t *bytes,
                                                           uintptr_t size,
                                                           float width,
                                                           float height,
                                                           float dx,
                                                           float dy);

bool canvas_native_ios_context_draw_image_dx_dy_dw_dh_with_bytes(int64_t context,
                                                                 uint8_t *bytes,
                                                                 uintptr_t size,
                                                                 float width,
                                                                 float height,
                                                                 float dx,
                                                                 float dy,
                                                                 float d_width,
                                                                 float d_height);

bool canvas_native_ios_context_draw_image_with_bytes(int64_t context,
                                                     uint8_t *bytes,
                                                     uintptr_t size,
                                                     float width,
                                                     float height,
                                                     float sx,
                                                     float sy,
                                                     float s_width,
                                                     float s_height,
                                                     float dx,
                                                     float dy,
                                                     float d_width,
                                                     float d_height);

void canvas_native_ios_context_custom_with_buffer_flush(int64_t context,
                                                        uint8_t *bytes,
                                                        uintptr_t size,
                                                        float width,
                                                        float height,
                                                        bool alpha);

long long canvas_native_ios_context_init_context_with_custom_surface(float width,
                                                                     float height,
                                                                     float density,
                                                                     bool alpha,
                                                                     int font_color,
                                                                     float ppi,
                                                                     int direction);

void canvas_native_ios_webgl_tex_image_2d(int64_t context,
                                          int32_t target,
                                          int32_t level,
                                          int32_t internalformat,
                                          int32_t format,
                                          int32_t type_,
                                          uint8_t *bytes,
                                          uintptr_t size,
                                          float width,
                                          float height,
                                          bool flip_y);

void canvas_native_ios_webgl_tex_sub_image_2d(int64_t context,
                                              int32_t target,
                                              int32_t level,
                                              int32_t xoffset,
                                              int32_t yoffset,
                                              int32_t format,
                                              int32_t type_,
                                              uint8_t *bytes,
                                              uintptr_t size,
                                              float width,
                                              float height,
                                              bool flip_y);

int64_t canvas_native_ios_create_2d_context_metal(void *view,
                                                  bool alpha,
                                                  float density,
                                                  uintptr_t samples,
                                                  int32_t font_color,
                                                  float ppi,
                                                  int32_t direction);

int64_t canvas_native_ios_create_2d_context_metal_offscreen(float width,
                                                            float height,
                                                            bool alpha,
                                                            float density,
                                                            uintptr_t samples,
                                                            int32_t font_color,
                                                            float ppi,
                                                            int32_t direction);

int64_t canvas_native_ios_create_2d_context_metal_device_queue(void *view,
                                                               void *device,
                                                               void *queue,
                                                               bool alpha,
                                                               float density,
                                                               uintptr_t samples,
                                                               int32_t font_color,
                                                               float ppi,
                                                               int32_t direction);

long long canvas_native_init_ios_webgpu(int64_t instance,
                                        void *view,
                                        uint32_t width,
                                        uint32_t height);

#if defined(TARGET_OS_MACOS)
long long canvas_native_init_ios_webgpu_nsview(int64_t instance,
                                               void *view,
                                               uint32_t width,
                                               uint32_t height);
#endif

#if defined(TARGET_OS_IOS)
void canvas_native_resize_ios_webgpu_uiview(int64_t context,
                                            void *view,
                                            uint32_t width,
                                            uint32_t height);
#endif

#endif /* CANVAS_IOS_H */
