[package]
name = "canvas-c"
version = "0.1.0"
edition = "2021"

[features]
2d = ["dep:canvas-2d"]
webgl = ["dep:canvas-webgl"]

[dependencies]
gl-bindings = { path = "../gl-bindings" }
canvas-core = { path = "../canvas-core", features = ["2d"] }
canvas-2d = { path = "../canvas-2d", optional = true, features = ["gl"] }
canvas-webgl = { path = "../canvas-webgl", optional = true }
parking_lot = "0.12.0"
ureq = { version = "2.9.6", features = ["gzip"] }
bytes = "1.5.0"
log = { version = "0.4.20" }
wgpu-types = { version = "22.0.0" }
futures = "0.3"
raw-window-handle = "0.6.2"
wgpu-core = { version = "22.0.0", features = ["wgsl", "vulkan", "metal", "raw-window-handle"] }

[target.'cfg(target_os="ios")'.dependencies]
display-link = {version = "0.2.0"}
wgpu-core = {version = "22.0.0", features = ["wgsl", "metal","raw-window-handle"]}


#[target.'cfg(target_os="macos")'.dependencies]
#display-link = { git = "https://github.com/servo/display-link", branch = "no-transmute" }
#wgpu-core = { version = "22.0.0", features = ["wgsl", "metal", "raw-window-handle"] }

[target.'cfg(target_os="android")'.dependencies]
ndk = { version = "0.7.0", features = ["bitmap"] }
once_cell = "1.14.0"
wgpu-core = { version = "22.0.0", features = ["wgsl", "vulkan", "raw-window-handle"] }