[package]
name = "canvas-c"
version = "0.1.0"
edition = "2021"

[features]
2d = ["dep:canvas-2d"]
webgl = ["dep:canvas-webgl"]
gl = ["canvas-2d/gl"]
vulkan = []
metal = ["canvas-2d/metal"]

[dependencies]
gl-bindings.workspace = true
canvas-core = { workspace = true, features = ["2d"] }
canvas-2d = { workspace = true, optional = true, features = ["gl"] }
canvas-webgl = { workspace = true, optional = true }
parking_lot.workspace = true
ureq = { version = "2.9.6", features = ["gzip"] }
bytes = "1.5.0"
log = { version = "0.4.20" }
wgpu-types.workspace = true
futures = "0.3"
raw-window-handle.workspace = true
wgpu-core = { workspace = true, features = ["wgsl", "vulkan", "metal", "raw-window-handle"] }

[target.'cfg(target_os="ios")'.dependencies]
display-link = { version = "0.2.0" }
wgpu-core = { workspace = true, features = ["wgsl", "metal", "raw-window-handle"] }


#[target.'cfg(target_os="macos")'.dependencies]
#display-link = { git = "https://github.com/servo/display-link", branch = "no-transmute" }
#wgpu-core = { version = "22.0.0", features = ["wgsl", "metal", "raw-window-handle"] }

[target.'cfg(target_os="android")'.dependencies]
ndk = { version = "0.7.0", features = ["bitmap"] }
wgpu-core = { workspace = true, features = ["wgsl", "vulkan", "raw-window-handle"] }