[package]
name = "canvas-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "canvasffi"
crate-type = ["staticlib"]

[features]
2d = ["dep:canvas-2d"]
webgl = ["dep:canvas-webgl"]


[build-dependencies]
cbindgen = "0.24.3"

[dependencies]
gl-bindings = { path = "../gl-bindings" }
canvas-core = { path = "../canvas-core" }
canvas-2d = { path = "../canvas-2d", optional = true }
canvas-webgl = { path = "../canvas-webgl", optional = true }
skia-bindings = { version = "0.58.0", features = ["gl"] }
skia-safe = { version = "0.58.0", features = ["gl"] }
css-color-parser = "0.1.2"