[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
  "-C", "target-cpu=native",
  "-C", "panic=abort"
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
  "-C", "target-cpu=native",
  "-C", "panic=abort"
]


[target.x86_64-apple-ios]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
  "-C", "target-cpu=native",
  "-C", "panic=abort"
]

[target.aarch64-apple-ios]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
  "-C", "target-cpu=native",
  "-C", "panic=abort"
]

[target.armv7-linux-androideabi]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "panic=abort",
  "-C", "target-feature=-outline-atomics"
]

[target.aarch64-linux-android]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "panic=abort",
  "-C", "target-feature=-outline-atomics"
]

[target.i686-linux-android]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "panic=abort",
  "-C", "target-feature=-outline-atomics"
]

[target.x86_64-linux-android]
rustflags = [
  "-C", "target-cpu=native",
  "-C", "panic=abort",
  "-C", "target-feature=-outline-atomics"
]