name: Canvas Native

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

env:
  NPM_TAG: "pr"
  EMULATOR_NAME: "runtime-emu"
  NDK_VERSION: r23c
  ANDROID_API: 29
  ANDROID_ABI: x86_64
  NDK_ARCH: linux


jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    outputs:
      npm_version: ${{ steps.npm_version_output.outputs.NPM_VERSION }}
      npm_tag: ${{ steps.npm_version_output.outputs.NPM_TAG }}
    steps:
    - name: Install rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
          submodules: true
    - uses: actions/setup-node@v3
      with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
    - uses: actions/setup-java@v3
      with:
          distribution: "temurin"
          java-version: "17"
          cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Setup NDK
      run: |
          echo "y" | sdkmanager "cmake;3.6.4111459"
          wget https://dl.google.com/android/repository/android-ndk-$NDK_VERSION-$NDK_ARCH.zip
          chmod +x android-ndk-$NDK_VERSION-$NDK_ARCH.zip
          unzip -q android-ndk-$NDK_VERSION-$NDK_ARCH.zip
          rm -rf android-ndk-$NDK_VERSION-$NDK_ARCH.zip
          export ANDROID_NDK_HOME=`pwd`/android-ndk-$NDK_VERSION
          echo ANDROID_NDK_HOME=${ANDROID_NDK_HOME} >> $GITHUB_ENV
          echo ANDROID_NDK=${ANDROID_NDK_HOME} >> $GITHUB_ENV
          echo ${ANDROID_NDK_HOME} >> $GITHUB_PATH
    
