[package]
name = "canvas-c"
version = "0.1.0"
edition = "2021"

[build]
rustflags = ["-Cpanic=abort", "-C target-cpu=native", "-C target-feature=-outline-atomics"]

[features]
2d = ["dep:canvas-2d"]
webgl = ["dep:canvas-webgl"]

[dependencies]
gl-bindings = { path = "../gl-bindings" }
canvas-core = { path = "../canvas-core", features = ["2d"] }
canvas-2d = { path = "../canvas-2d", optional = true, features = ["gl"] }
canvas-webgl = { path = "../canvas-webgl", optional = true }
parking_lot = "0.12.0"
ureq = { version = "2.9.6", features = ["gzip"] }
bytes = "1.5.0"
ada-url = "2.2.1"
log = { version = "0.4.20"}

[target.'cfg(target_os="ios")'.dependencies]
display-link = "0.2.0"
#ada-url = "2.1.0"
#[target.'cfg(target_os="macos")'.dependencies]
#display-link = "0.2.0"

[target.'cfg(target_os="android")'.dependencies]
ndk = { version = "0.7.0", features = ["bitmap"] }
once_cell = "1.14.0"