[package]
name = "canvas-2d"
version = "0.1.0"
edition = "2021"

[features]
metal = ["skia-safe/metal"]
gl = ["skia-safe/gl"]

[dependencies]
canvas-core = { path = "../canvas-core", features = ["2d"] }
parking_lot = "0.12.1"
regex = "1.5.4"
base64 = "0.21.0"
encoding_rs = "0.8.32"
gl-bindings = { path = "../gl-bindings" }
lazy_static = "1.4.0"
csscolorparser = { git = "https://github.com/triniwiz/csscolorparser-rs.git", rev = "c8c7e86", features = ["named-colors"] }
rgb = { version = "0.8.32", features = ["argb"] }
log = "0.4.8"
once_cell = "1.8.0"
skia-bindings = { version = "0.66.2", features = ["gl", "svg"] }
skia-safe = { version = "0.66.2", features = ["gl", "svg"] }
image = {version = "0.24.5" , features = ["png", "jpeg", "gif"]}